language: python
cache: pip
python:
  - "3.4"
  - "nightly"
env: TOXENV=py

matrix:
  fast_finish: true
  include:
    - python: 3.3
      # This is required to run Python 3.3 on Travis
      dist: trusty
      env: TOXENV=py33 # Needed because "py" won't invoke testenv:py33
  allow_failures:
    - python: "nightly"

install:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then
      pip install -U "pip==10.0.1"
      PIP_ARGS="-c requirements/3.3/constraints.txt"
    fi
  - |
    if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then
      pip install -U setuptools
    fi
  - pip install -U "tox<3.8.0" $PIP_ARGS
  - if [[ $TOXENV == "py" ]]; then ./ci_tools/retry.sh python updatezinfo.py; fi

script:
  - tox

after_success:
  - if [[ $TOXENV == "py" ]]; then tox -e coverage,codecov; fi
